theme = "base16_transparent"

[editor]
true-color = true
mouse = false

[keys.normal]
"ret" = ":write"

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
left = ["mode", "file-base-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control"]
right = ["spinner", "position"]
