theme = "luwe_transparent"

[editor]
true-color = true
color-modes = true
mouse = false

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

left = ["mode", "file-base-name", "file-modification-indicator", "read-only-indicator"]
center = ["version-control"]
right = ["spinner", "position"]


[keys.normal]
"ret" = ":write"
