[terminal.shell]
program = "fish"
args = ["--login"]

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[font]
size = 14

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[window]
opacity = 0.8

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 120
lines = 30
